[project]
name = "lesson_21"
version = "0.1.0"
description = "Visualization of Prim's algorithm"
dependencies = ["networkx", "matplotlib", "streamlit"]

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
